In [1]:
print(1)

1


In [10]:
import numpy as np
array1=np.array([1,2,3,4,5])#一维数组
print(array1)
array2=np.array([[1,2,3],[4,5,6]])#二维数组
print(array2)
array3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])#三维数组
print(array3.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
(2, 2, 3)


In [16]:
array4=np.array(array1)#array()直接复制参数的内容，相当于深拷贝
print(id(array1))#查看Array1的地址
print(id(array4))#查看array4的地址
array5=np.asarray(array1)#asarray()相当于浅拷贝
print(id(array5))

2484069012400
2484069257200
2484069012400


In [27]:
# zeros()：返回给定形状和类型的新数组，用0填充。
# ones()：返回给定形状和类型的新数组，用1填充。
# empty()：返回给定形状和类型的未初始化的新数组。
# 需要注意的是，np.empty 并不保证数组元素被初始化为 0，它只是分配内存空间，数组中的元素值是未初始化的，可能是内存中的任意值。
# 上述3个方法创建的数组元素类型默认都是float64。
# zeros_like()：返回与给定数组具有相同形状和类型的0新数组。
# ones_like()：返回与给定数组具有相同形状和类型的1新数组。
# empty_like()：返回与给定数组具有相同形状和类型的未初始化的新数组。
# array6=np.zeros((3,4))
# print(array6)
array6=np.ones((3,4))
print(array6)
# array6=np.empty((4,4))
# print(array6)
array7=np.zeros_like(array6)
print(array7)
array7=np.ones_like(array6)
print(array7)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
# full()：返回给定形状和类型的新数组，用指定的值填充。
# full_like()：返回与给定数组具有相同形状和类型的用指定值填充的新数组。
import numpy as np
array=np.full((3,4),5)
print(array)
array=np.full_like(array,6)
print(array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [4]:
# arange()：返回在给定范围内用均匀间隔的值填充的一维数组。
array=np.arange(0,10,1)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# linspace()：返回指定范围和元素个数的等差数列。数组元素类型为浮点型。
# logspace()：返回指定指数范围、元素个数、底数的等比数列。
array=np.linspace(0,10,5)
print(array)
array=np.logspace(1,10,5)
print(array)
# arr2 = np.linspace(start=0, stop=10, num=5, endpoint=False)  # 设置endpoint=False，表示不包括stop
# # [0. 2. 4. 6. 8.]
#
# arr3 = np.logspace(start=2, stop=5, num=5, base=2)
# # [ 4. 6.72717132 11.3137085  19.02731384 32.

[ 0.   2.5  5.   7.5 10. ]
[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [13]:
# random.rand()：返回给定形状的数组，用 [0, 1) 上均匀分布的随机样本填充。
# random.randint()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机整数填充。
# random.uniform()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机浮点数填充。
# random.randn()：返回给定形状的数组，用标准正态分布(均值为0，标准差为1)的随机样本填充。
array1=np.random.rand(2,3)
print(array1)
array1=np.random.randint(0,10,(2,3))
print(array1)
array1=np.random.uniform(0,10,(2,3))
print(array1)
array1=np.random.randn(2,3)
print(array1)

[[0.66970395 0.89514615 0.45997613]
 [0.67014078 0.8101702  0.73374227]]
[[0 0 7]
 [1 5 2]]
[[5.96327718 4.82462659 7.21606873]
 [1.68535584 6.37696297 5.92944736]]
[[ 0.06339671 -1.27206874  0.0508027 ]
 [ 0.91792275  0.42267281  0.07394719]]


In [14]:
# matrix为ndarray的子类，只能生成二维的矩阵
arr1 = np.matrix("1 2; 3 4")
print(arr1)
arr2 = np.matrix([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [16]:
#创建数组时可以使用dtype参数指定元素类型：
array=np.array([1,2,3],dtype=np.float64)
print(array)
#也可以使用ndarray.astype()方法转换数组的元素类型
arr2 = array.astype(np.int64)
print(arr2)

[1. 2. 3.]
[1 2 3]


In [20]:
# ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。
# 可以通过内置的slice函数，或者冒号设置start, stop及step参数进行切片，从原数组中切割出一个新数组。
array=np.arange(10)
print(array[1])
print(array[2:5:1])#下标2-5中间间隔1
print(array[slice(2,5,1)])
print(array[2:])

1
[2 3 4]
[2 3 4]
[2 3 4 5 6 7 8 9]


In [26]:
array=np.array([[1,2,3,4],[2,3,4,5],[3,6,5,2]])
#遍历数组(1)
for i in array:
    for j in i:
      print(j)

1
2
3
4
2
3
4
5
3
6
5
2


In [30]:
#遍历数组(2)
i=0
j=0
for i in range(0,3):
    for j in range(0,4):
        print(array[i][j])

1
2
3
4
2
3
4
5
3
6
5
2


In [31]:
#遍历数组（3）：扁平化遍历
for i in array.flat:
    print(i)

1
2
3
4
2
3
4
5
3
6
5
2


In [33]:
#使用np.nditer,numpy专门提供的迭代器
# 默认按行优先（C order）
for x in np.nditer(array):
    print(x, end=" ")
print()
# 按列优先（Fortran order）
for x in np.nditer(array, order='F'):
    print(x, end=" ")

1 2 3 4 2 3 4 5 3 6 5 2 
1 2 3 2 3 6 3 4 5 4 5 2 

In [42]:
#数组排序
array=np.array([[8,9,3],[4,6,6],[7,4,9]])
array.sort(axis=1)#直接对数组本身进行排序默认行方向排序
array.sort(axis=0)#直接对数组本身进行排序此时方向是列的方向
print(array)
a=np.sort(array)#这个进行copy将结果返回


[[3 8 9]
 [4 6 6]
 [4 7 9]]


In [45]:
#对数组进行整体排序
array=np.array([[8,9,3],[4,6,6],[7,4,9]])
a1=np.sort(array,axis=None)#对整个数组进行排序
print(a1)

[3 4 4 6 6 7 8 9 9]


In [48]:
#数组去重，返回一个有序数组
array=np.array([[8,9,3],[4,6,6],[7,4,9]])
a=np.unique(array)
print(a)
print()
array=np.array([[8,9,3],[4,6,6],[7,4,9]])
a1=np.sort(array,axis=None)#对整个数组进行排序
a2=np.unique(a1)
print(a5)

[3 4 6 7 8 9]

[3 4 6 7 8 9]
